"""Teleportation Protocol Implementation
    This module implements the teleportation protocol for quantum communication.   
    It includes the core logic for Alice's and Bob's sides of the teleportation process,
    handling entangled states, and applying corrections based on classical messages.
"""

from enum import Enum, auto
from .base_teleport import BaseTeleportMsgType, BaseTeleportMessage, BaseTeleportProtocol
from ...network_management.reservation import Reservation
from ...utils import log


class TeleportMsgType(Enum):
    """Enumeration for different types of teleportation messages."""
    MEASUREMENT_RESULT = auto() # Alice informs Bob of her measurement result
    ACK = auto()                # Bob acknowledges Alice the teleportation is complete


class TeleportMessage(BaseTeleportMessage):
    """Classical message used to convey the Pauli corrections (x, z) from
    sender to receiver during teleportation.

    Attributes:
        reservation (Reservation): The reservation object associated with this teleportation message.
        bob_comm_memory_name (str): Name of the memory on Bob's side to be corrected.
        x_flip (int): MEASUREMENT_RESULT only, whether to apply X correction (1 for yes, 0 for no).
        z_flip (int): MEASUREMENT_RESULT only, whether to apply Z correction (1 for yes, 0 for no).
    """
    def __init__(self, msg_type: TeleportMsgType, **kwargs):
        # Map to base enum values
        base_msg_type = BaseTeleportMsgType.MEASUREMENT_RESULT if msg_type == TeleportMsgType.MEASUREMENT_RESULT else BaseTeleportMsgType.ACK
        super().__init__(base_msg_type, 'teleport_app', **kwargs)


class TeleportProtocol(BaseTeleportProtocol):
    """Core teleportation logic:
     - handle_entangled(): invoked when a comm-memory becomes ENTANGLED
     - handle_correction(): invoked when Bob receives Alice's classical bits

    NOTE: the teleport protocol is not generated by the Rule system
           Can it be? Seems pretty hard to be generated by the Rule system
    NOTE: this protocol is asymmetric, alice and bob behave very differently

    Attributes:
        owner (DQCNode): The node that owns this protocol.
        data_memory (str): The name of the data memory to teleport on Alice's side.
        alice (bool): Whether this protocol plays the Alice role.
        name (str): The name of the teleport protocol.
        remote_node_name (str): The name of the remote node (Bob) involved in the teleportation.
        alice_comm_memory_name (str): The name of the communication memory on Alice's side.
        alice_comm_memory (Memory): The communication memory on Alice's side.
        bob_comm_memory_name (str): The name of the communication memory on Bob's side.
        bob_comm_memory (Memory): The communication memory on Bob's side.
    """

    def __init__(self, owner, alice: bool = False, data_memory_index: int = None, remote_node_name: str = None):
        """ Initialize the teleportation protocol.
            
        Args:
            owner (QuantumNode): The node that owns this protocol.
            alice (bool): Whether this protocol plays the Alice role.
            data_memory_index (int): The index of the data memory to teleport.
            remote_node_name (str): The name of the other node involved in the teleportation.
        """
        super().__init__(owner, alice, data_memory_index, remote_node_name, "teleport")

    def _send_measurement_result(self, reservation: Reservation, x: int, z: int):
        """Send measurement result to Bob."""
        msg = TeleportMessage(TeleportMsgType.MEASUREMENT_RESULT, bob_comm_memory_name=self.bob_comm_memory_name, x_flip=x, z_flip=z, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)

    def _apply_post_correction_logic(self, msg):
        """Apply teleportation-specific logic after corrections."""
        self.owner.teleport_app.teleport_complete(self.bob_comm_memory.qstate_key)

    def _send_acknowledgment(self, reservation: Reservation):
        """Send acknowledgment to Alice."""
        msg = TeleportMessage(TeleportMsgType.ACK, bob_comm_memory_name=self.bob_comm_memory_name, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)
        log.logger.debug(f"{self.name}: sent ACK to {self.remote_node_name}")
