"""Teledata Protocol Implementation
    This module implements the teledata protocol for quantum communication.   
    It includes the core logic for Alice's and Bob's sides of the teledata process,
    handling entangled states, and applying corrections based on classical messages.
"""

from enum import Enum, auto
from ...components.circuit import Circuit
from .base_teleport import BaseTeleportMsgType, BaseTeleportMessage, BaseTeleportProtocol
from ...network_management.reservation import Reservation
from ...utils import log


class TeledataMsgType(Enum):
    """Enumeration for different types of teledata messages."""
    MEASUREMENT_RESULT = auto() # Alice informs Bob of her measurement result
    ACK = auto()                # Bob acknowledges Alice the teledata is complete


class TeledataMessage(BaseTeleportMessage):
    """Classical message used to convey the Pauli corrections (x, z) from
    sender to receiver during teledata.

    Attributes:
        reservation (Reservation): The reservation object associated with this teledata message.
        bob_comm_memory_name (str): Name of the memory on Bob's side to be corrected.
        x_flip (int): MEASUREMENT_RESULT only, whether to apply X correction (1 for yes, 0 for no).
        z_flip (int): MEASUREMENT_RESULT only, whether to apply Z correction (1 for yes, 0 for no).
        bob_data_memory_index (int): MEASUREMENT_RESULT only, target data memory slot on Bob's side.
    """
    def __init__(self, msg_type: TeledataMsgType, **kwargs):
        # Map to base enum values
        base_msg_type = BaseTeleportMsgType.MEASUREMENT_RESULT if msg_type == TeledataMsgType.MEASUREMENT_RESULT else BaseTeleportMsgType.ACK
        super().__init__(base_msg_type, 'teledata_app', **kwargs)


class TeledataProtocol(BaseTeleportProtocol):
    """Core teledata logic:
     - handle_entangled(): invoked when a comm-memory becomes ENTANGLED
     - handle_correction(): invoked when Bob receives Alice's classical bits

    NOTE: the teledata protocol is not generated by the Rule system
           Can it be? Seems pretty hard to be generated by the Rule system
    NOTE: this protocol is asymmetric, alice and bob behave very differently

    Attributes:
        owner (DQCNode): The node that owns this protocol.
        data_memory (str): The name of the data memory to teleport on Alice's side.
        alice (bool): Whether this protocol plays the Alice role.
        name (str): The name of the teledata protocol.
        remote_node_name (str): The name of the remote node (Bob) involved in the teledata.
        alice_comm_memory_name (str): The name of the communication memory on Alice's side.
        alice_comm_memory (Memory): The communication memory on Alice's side.
        bob_comm_memory_name (str): The name of the communication memory on Bob's side.
        bob_comm_memory (Memory): The communication memory on Bob's side.
    """
    
    # SWAP circuit to move teleported state from comm to data memory
    _swap_circuit = Circuit(2)
    _swap_circuit.cx(0, 1)  # comm_qubit -> data_qubit
    _swap_circuit.cx(1, 0)  # data_qubit -> comm_qubit  
    _swap_circuit.cx(0, 1)  # comm_qubit -> data_qubit

    def __init__(self, owner, alice: bool = False, data_memory_index: int = None, remote_node_name: str = None):
        """ Initialize the teledata protocol.
            
        Args:
            owner (QuantumNode): The node that owns this protocol.
            alice (bool): Whether this protocol plays the Alice role.
            data_memory_index (int): The index of the data memory to teleport.
            remote_node_name (str): The name of the other node involved in the teledata.
        """
        super().__init__(owner, alice, data_memory_index, remote_node_name, "teledata")

    def _send_measurement_result(self, reservation: Reservation, x: int, z: int):
        """Send measurement result to Bob."""
        msg = TeledataMessage(TeledataMsgType.MEASUREMENT_RESULT, bob_comm_memory_name=self.bob_comm_memory_name, x_flip=x, z_flip=z, bob_data_memory_index=self.data_memory_index, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)
        log.logger.info(f"{self.name}: sent measurement results to {self.remote_node_name}: bob_comm_memory={self.bob_comm_memory_name}, x={x}, z={z}, bob_data_memory_index={self.data_memory_index}, reservation={reservation}")

    def _apply_post_correction_logic(self, msg):
        """Apply teledata-specific logic after corrections."""
        # Get Bob's data memory key for the target slot
        data_memory_array = self.owner.get_component_by_name(self.owner.data_memo_arr_name)
        # Use modulo to handle cases where the target index exceeds available memory slots
        target_slot = msg.bob_data_memory_index % len(data_memory_array.memories)
        bob_data_memory_key = data_memory_array[target_slot].qstate_key
        
        # SWAP the teleported state from comm memory to data memory
        rnd = self.owner.get_generator().random()
        self.owner.timeline.quantum_manager.run_circuit(
            TeledataProtocol._swap_circuit, [self.bob_comm_memory.qstate_key, bob_data_memory_key], rnd
        )
        log.logger.info(f"{self.name}: SWAP applied - teleported state moved from comm to data memory slot {target_slot} (requested {msg.bob_data_memory_index})")

        # Notify app that the teleported state is now in the data memory
        self.owner.teledata_app.teledata_complete(bob_data_memory_key)

    def _send_acknowledgment(self, reservation: Reservation):
        """Send acknowledgment to Alice."""
        msg = TeledataMessage(TeledataMsgType.ACK, bob_comm_memory_name=self.bob_comm_memory_name, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)
        log.logger.debug(f"{self.name}: sent ACK to {self.remote_node_name}")
